server:
  http:
    addr: 192.168.2.85:8081
    timeout: 1s
  grpc:
    addr: 192.168.2.85:50057
    timeout: 1s
  consul:
    addr: 192.168.2.85:8500
data:
  database:
    driver: mysql
    source: root:123456@(127.0.0.1:3306)/closer_user
  redis:
    addr: 192.168.2.85:6379
    db: 12
    read_timeout: 0.2s
    write_timeout: 0.2s
service:
  register:
    id: userService
    name: grpc.user.v1
    tag: [用户服务]
  check:
    interval: 10s
    timeout: 1s
    notes: Consul check userService health status.
    deregistercriticalserviceafter: 30s
